### ISSUE TITLE
Read Only WebUI

### ISSUE THREAD

**Issue by OneGeekyDad** [ChrisRomp/hamclock-docker#59]
I am not familiar with the interworking's of Docker.  Is there a way to pass along the -r parameter to lock down changes to the web interface?

Thanks

Josh

**Comment by OneGeekyDad** [comment]
Here is my yaml: 
#version: "3"
services:
  web:
    image: ghcr.io/chrisromp/hamclock-docker:latest
    ports:
      - "8080:8080/tcp"
      - "8081:8081/tcp"
    volumes:
      - data:/root/.hamclock
    restart: unless-stopped

volumes:
  data:

**Comment by ChrisRomp** [comment]
Try this:

```yml
#version: "3"
services:
web:
image: ghcr.io/chrisromp/hamclock-docker:latest
ports:
  - "8080:8080/tcp"
  - "8081:8081/tcp"
volumes:
  - data:/root/.hamclock
restart: unless-stopped
command:
  - /usr/local/bin/hamclock
  - -o
  - -w
  - "-1"
  - -r
  - 8081
volumes:
data:
```

This _should_ be the equivalent of `hamclock -o -w -1 -r 8081`.
- `-o` logs to stdout (this is part of the built-in command and makes the docker logs more useful)
- `-w -1` disables the read/write web interface (defaults to 8081)
- `-r 8081` runs the read-only web interface on 8081 (defaults to 8082)

Ref: https://inovato.net/ham/HamClockUserGuide.pdf (page 17) -- feel free to adjust the command arguments as you wish.

If that doesn't work I can try to test some things and see how to make it work.
