### ISSUE TITLE
Not compatible with VPS using Arm64/Ampere architecture

### ISSUE THREAD

**Issue by pierdom** [ChrisRomp/hamclock-docker#70]
Hello and thank you for your work. 
I have been using your pre-built image to run HamClock on a Raspberry Pi for more than a year now.
I have tried to run it on an VPS that uses Ampere architecture (quite popular with cloud providers). The cloud provider is Hetzner and the OS is Debian bookwork.

**Symptoms**
When I run your image, HamClock exits with error 132, which is typically related to incompatible architecture.
It looks strange at first, because Ampere is an arm64 CPU similar to the one on the Raspberry Pi, but after some investigation I discovered that it has a rather different feature set.

**Potential solution**
use flags to make compile safer and avoid using instructions that the Raspberry PI CPU supports, but the cloud one does not.
The flags are `-march=armv8-a` and `-mtune=generic`.

**Suggested changes**
Pass the flags from the Github actions task to the Dockerfile-CI:
```
- name: Build Docker image
  id: build-and-push
  uses: docker/build-push-action@v6
  with:
    context: .
    file: Dockerfile-CI
    platforms: linux/arm64
    push: true
    tags: ghcr.io/chrisromp/hamclock-docker:test-arm64
    no-cache: true
    build-args: |
      CFLAGS=-O2 -march=armv8-a -mtune=generic
```

Then, use those flags in the Dockerfile-CI file to compile correctly:
```
RUN make -j 4 hamclock-web-${HAMCLOCK_RESOLUTION} CFLAGS="${CFLAGS}"
```

Note: I investigated the problem a bit (I am no expert), but I am not able to test this solution right now.
I hope it helps!

Regards
